# roles/aws-elb/tasks/main.yml

# Create ELB and dependencies 

- name: Lookup subnet info
  ec2_vpc_subnet_info:
    filters:
      "tag:Name": "{{ item }}"
  loop: "{{ elb_subnet_names }}"
  register: subnet_info

- name: Lookup target EC2 info
  ec2_instance_info:
    filters:
      "tag:Name": "{{ elb_target_ec2_name }}"
  register: ec2_info

- name: Lookup security group info
  ec2_group_info:
    filters:
      group-name: "{{ elb_sg_name }}"
  register: sg_info  

- name: 
  ec2_elb_lb:
    name: "{{ elb_name }}"
    state: present
    subnets: "{{ subnet_info.results | sum(attribute='subnets', start=[]) | map(attribute='id') | list }}" 
    instance_ids: "{{ ec2_info|json_query('instances[*].instance_id') }}"
    security_group_ids: "{{ sg_info|json_query('security_groups[*].group_id') }}"
    listeners: "{{ elb_listeners }}"
    health_check: "{{ elb_health_check }}
  register: elb_info

- debug: 
    var: elb_info
